version: '3'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat-1.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs
      - ./data:/usr/share/filebeat/data
    ports:
      - "5044:5044"
    restart: unless-stopped