filebeat.inputs:
- type: tcp
  host: "0.0.0.0:5140"
  enabled: true
  max_message_size: 10MB
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~
  - add_fields:
      target: ''
      fields:
        environment: 'development'

# Add a processor to parse the JSON in the message field if needed
  - decode_json_fields:
      fields: ["message"]
      target: ""
      process_array: false
      max_depth: 10
      overwrite_keys: true
      add_error_key: true
      when:
        has_fields: ['message']

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "finance-%{+yyyy.MM.dd}"
      when.equals:
        service: "finance"
    - index: "authentication-%{+yyyy.MM.dd}"
      when.equals:
        service: "authentication"
    - index: "subscription-%{+yyyy.MM.dd}" 
      when.equals:
        service: "subscription"
    - index: "logs-%{+yyyy.MM.dd}"